Dev to main #6
SiarheiNeparka/my_news_site_project pull request #10
Opened 2024-04-04 14:37 UTC by SiarheiNeparka

Как я понимаю, - после того, как я воспользовался функционалом для очистки репозитория от .cfg файла, после того, как поздно заметил, что он улетел в облако, - стало невозможно запушить изменения на репозиторий из ветки dev, а после того, как я с помощью гугла, всё же, запушил, - невозможно было создать pull request. Ветки не сопостовлялись. Опять же, с помощью гугла я пытался восстановить справедливость, так скажем, и всё пришло к тому, что я просто потерял всю историю коммитов относительно крайнего задания. Я удалил все коммиты из main и dev до момента предыдущего pull request'a без вызова сборщика мусора, заново выполнил предыдущий мёрдж №5 и переделал всё по актуальному заданию заново, но более бегло, чтобы открыть данный пул реквест. К сожалению моих знаний не хватает для того, чтобы понять, как это можно было сделать грамотно. Нынче он мне показывает, что коммиты мэйна (коммиты мерджей, как я понимаю) не состыковываются с дэв веткой. Так было всегда? И так будет всегда, при выбранной стратегии?

В данном пул реквесте находятся:
- страница с формой для отправки новости по email (в т. ч. и стилизация оформления формы) (могу попросить объяснить как сделать так, чтобы ссылка на share не строиласть на базе id, а строилась на базе ссылки той новости, которую шарим (мы же специально делали ссылку из даты и текста ранее)?);
- кавычки приведены к единому стилю во всех файлах;
- создан файл requirements.txt (проект работает на django 4.2.7 (нужная версия взята из гугла; на 4.1 выдаёт ошибку SMTP.starttls() got an unexpected keyword argument 'keyfile')).

Переход на предложенные версии по инструкции, предоставленной в телеграмме выполнил, но, - ошибка не ушла. Решение без перехода на более новые версии нашёл здесь: https://github.com/PacktPublishing/Django-4-by-example/issues/41
Необходимо было скачать и заменить один файл внутри самого django, и, - всё заработало. Нынче проект работает на django 4.1 и python 3.10.11.

Также были добавлены следующие функциональности:
- возможность оставлять комментарии к новостям;
- возможность навигации по тегам.

Кроме этого все url'ы приведены к каноническому виду.

Бесконечный пул реквест разрастается дальше:
- были добавлены рекомендации к статьям на основе схожих тегов;
- в сайдбаре была добавлена новая информация (общее кол-во опубликованных статей на сайте, самые свежие новости, самые обсуждаемые новости), используя кастомные теги;
- был добавлен кастомный фильтр, обрабатывающий маркдаун-синтаксис;
- была добавлена xml-карта сайта;
- была добавлена RSS-лента сайта.

Снова:
- проект переведён с SQLite на PostgreSQL;
- на сайте реализован поиск по новостям (для этого существует отдельная страница);
- панель навигации расширена ссылками на поисковую страницу и страницу с картой сайта, а так же перегруппирована.

И опять:
- реализована функциональность сообщений (messages), всплывающих над сайдбаром (разработка велась в ветке feature_messages, после чего был сделан rebase этой ветки в dev по инструкции из первых лекций, но, как оказалось, - перенеслись все коммиты из feature_messages, а в задании было сказано перенести последний коммит; буду разбираться дальше как это сделать);
- реализован дебаг тулбар (разработка велась в ветке feature_debug, после чего ветка была запушена, затем в интерактивном режиме ребейса все коммиты объеденены в один, и был выполнен ребейс ветки dev; думаю, что сделал неверно, ибо теперь на удалённом репозитории у меня несколько коммитов в ветке feature_debug, а на локальном - один объединённый, который я не пушил после объединения; я не понимаю что значит "rebase last commit from ‘feature debug’ branch to ‘dev’ branch" в задании, ибо, как я понимаю, последний коммит будет содержать в себе лишь малую часть изменений, поэтому я и захотел объединить все в один, или же перенести все, как в первом случае, а не только последний; короче говоря, - первый вариант по мануалу, предоставленному ранее мне кажется более правильным, так что буду делать так до появления пояснений; благодарю);
- реализован подсчёт количества просмотров на новостях на основе редис, а также создана отдельная страница с топом новостей по количеству просмотров.

2024-04-16 15:12 UTC, udevgeektutor requested changes

2024-04-16 15:12 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
Можно сделать проще)

2024-04-16 15:29 UTC, SiarheiNeparka commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
@udevgeektutor, каким образом?

2024-04-16 17:15 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
изучить документацию функции path, просмотреть прошлые примеры использования в проекте.
+тут явно чтото не то, похоже и на опечатку и на избыточность.
во вьюшке ты импортируешь sitemap, зачем тут писать для контекста передавать такое сложное имя как строку ---> 'django.sontrib.sitemaps.views.sitemap'?
```suggestion
                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
```

2024-04-16 17:15 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
А такое разве существет?
'django.sontrib'

2024-04-16 17:16 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
до шаблона код можно донести хотя бы так
```suggestion
                <a href="{% url 'sitemaps' %}">XML-карта сайта</a>
```

2024-04-16 17:20 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
естественн подогнав вьюшку под это)

2024-04-16 17:30 UTC, udevgeektutor requested changes

2024-04-16 17:30 UTC, udevgeektutor commented on mywebsite/mywebsite/urls.py
> +    ),
зачем тут для контекста передавать такое сложное имя как строку?

2024-04-16 17:30 UTC, udevgeektutor commented on mywebsite/mywebsite/settings.py
> +conf = configparser.ConfigParser()
Попробуй конфиги немного структурировать.

Типа коммент поясняющий что за конфиг
блок с загрузкой конфигов 
коммент поясняющий что за конфиг
блок с загрузкой конфигов 

+чтобы они располагались в одной области кода, по порядку, а не разбросаны по всему коду

2024-04-16 17:45 UTC, SiarheiNeparka commented on mywebsite/mywebsite/urls.py
> +    ),
Потому что так указано в лекции и во время обзора относительно урлов так и было сказано, мол, повторить не задумываясь; делается именно так, как здесь показано

2024-04-16 17:55 UTC, SiarheiNeparka commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
Не понимаю о чём речь. Если дело лишь в том, что нужно исправить опечатку в name, а лучше вообще сократить name - хорошо, сделаю. Так было в лекции (если не считать опечатки), а дальше я лишь сослался на нужный url. О каком подгоне вьюшки идёт речь - не понимаю: указанный код является частью base, который используется на всех вьюшках, а вьюшка для sitemap импортируется прямо в urls.py из числа встроенных

2024-04-16 17:56 UTC, SiarheiNeparka commented on mywebsite/mywebsite/settings.py
> +conf = configparser.ConfigParser()
Переработаю

2024-04-16 17:57 UTC, udevgeektutor commented on mywebsite/mywebsite/urls.py
> +    ),
где такое говорилось?
"сказано, мол, повторить не задумываясь; делается именно так, как здесь показано"

2024-04-16 17:59 UTC, udevgeektutor commented on mywebsite/mywebsite/urls.py
> +    ),
типа это функция
она принимает
name='django.sontrib.sitemaps.views.sitemap',

ты в шаблоне поэтому пишешь - django.sontrib.sitemaps.views.sitemap

Зечем? это не импорт, это просто строка
типа я могу написать 

name='blabla',
тогда и в шаблоне будет меньше писать, нет?
И на заметку, всё что дается - требует хотя бы чтения документации.
Про тупое переписывание - впервые слышу.

2024-04-16 18:06 UTC, SiarheiNeparka commented on mywebsite/mywebsite/urls.py
> +    ),
> где такое говорилось? "сказано, мол, повторить не задумываясь; делается именно так, как здесь показано"

Прислал в телеграм

2024-04-16 18:14 UTC, SiarheiNeparka commented on mywebsite/mywebsite/urls.py
> +    ),
@udevgeektutor, я понимаю для чего нужен name, но у меня не достаточно знаний для того, чтобы понять, что я действительно могу прописывать в ней что угодно удобное мне, когда впервые столкнулся с тем, что весь функционал sitemap автоматический. Было сказано прописать как есть, по шаблону, - я и прописал. Впредь буду знать, что этот параметр свободно можно изменять. Благодарю

2024-04-21 08:55 UTC, SiarheiNeparka commented on mywebsite/news/templates/news/base.html
> +                <a href="{% url 'django.sontrib.sitemaps.views.sitemap' %}">XML-карта сайта</a>
@udevgeektutor, сделано.

2024-04-21 08:55 UTC, SiarheiNeparka commented on mywebsite/mywebsite/settings.py
> +conf = configparser.ConfigParser()
@udevgeektutor, сделано.

2024-04-23 17:45 UTC, udevgeektutor approved these changes

2024-04-29 09:57 UTC, merged